magenta_user:
    resource: "@MagentaCBookAdminBundle/Resources/config/routing/all.xml"
    prefix: '%SYSTEM_PREFIX%'

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: '%SYSTEM_PREFIX%'

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: '%SYSTEM_PREFIX%'

sonata_media_gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

magenta_cbook:
    resource: "@MagentaCBookAdminBundle/Resources/config/routing/book.yaml"
    prefix: '%CBOOK_PREFIX%'

magenta_media_view_binary:
    path:      /media/view-binary/{id}/{format}
    controller: MagentaCBookAdminBundle:Media:viewBinary
    defaults:   { format: reference }


#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#fos_user_profile_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#fos_user_registration:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register