services:
    jms_serializer.media_listener:
        class: Magenta\Bundle\CBookModelBundle\EventListener\JMSSerializerMediaListener
        arguments:
            - '@service_container'
        tags:
            - {name: jms_serializer.event_listener, event: serializer.pre_serialize, class: 'Magenta\Bundle\CBookModelBundle\Entity\Media\Media', method: onPreSerialize }
