services:
    jms_serializer.media_listener:
        class: Magenta\Bundle\CBookModelBundle\EventListener\JMSSerializerMediaListener
        arguments:
            - '@service_container'
        tags:
            - {name: jms_serializer.event_listener, event: serializer.pre_serialize, class: 'Magenta\Bundle\CBookModelBundle\Entity\Media\Media', method: onPreSerialize }

    magenta_user.command.create_person:
        class: Magenta\Bundle\CBookModelBundle\Command\Person\CreatePersonCommand
        public: false
        arguments: ['@doctrine.orm.default_entity_manager']
        tags:
        - {name: "console.command", command: "magenta:person:create"}

    magenta_book.command.fix_chapter_position:
        class: Magenta\Bundle\CBookModelBundle\Command\Book\FixChapterPositionCommand
        public: false
        arguments: ['@doctrine.orm.entity_manager','@doctrine','@Magenta\Bundle\CBookModelBundle\Service\Book\BookService']
        tags:
        - {name: "console.command", command: "magenta:book:fix-chapter-position"}

    Magenta\Bundle\CBookModelBundle\Service\Spreadsheet\SpreadsheetService:
        class: Magenta\Bundle\CBookModelBundle\Service\Spreadsheet\SpreadsheetService
        arguments:
            - '@service_container'
        public: false

    magenta_book.spreadsheet_service:
        alias: 'Magenta\Bundle\CBookModelBundle\Service\Spreadsheet\SpreadsheetService'
        public: true

    Magenta\Bundle\CBookModelBundle\Service\Book\BookService:
        class: Magenta\Bundle\CBookModelBundle\Service\Book\BookService
        arguments:
        - '@service_container'
        - '@doctrine.orm.entity_manager'
        - '@doctrine'
        public: false

    magenta_book.book_service:
        alias: 'Magenta\Bundle\CBookModelBundle\Service\Book\BookService'
        public: true

    Magenta\Bundle\CBookModelBundle\Service\Person\PersonService:
        class: Magenta\Bundle\CBookModelBundle\Service\Person\PersonService
        arguments:
        - '@service_container'
        public: false

    magenta_book.person_service:
        alias: 'Magenta\Bundle\CBookModelBundle\Service\Person\PersonService'
        public: true

    Magenta\Bundle\CBookModelBundle\Service\Organisation\IndividualMemberService:
        class: Magenta\Bundle\CBookModelBundle\Service\Organisation\IndividualMemberService
        arguments:
        - '@service_container'
        public: false

    magenta_book.individual_service:
        alias: 'Magenta\Bundle\CBookModelBundle\Service\Organisation\IndividualMemberService'
        public: true
