bean_dev_tool:
    library_source: \workspace\libraries\cbook\
    library_workspace: \workspace\magenta\cbook\system\libraries\
    components: ~
    bundles:
        - BeanSonataMediaBundle
        - BeanBookBundle
        - BeanCreativeWorkBundle
        - BeanMediaBundle
        - BeanPersonBundle
        - BeanThingBundle
        - BeanOrganizationBundle

        - MagentaCBookAdminBundle
        - MagentaCBookModelBundle
        - MagentaCBookJWTBundle
