magenta_book_pwa_push_notif_read:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/notif/{messageId}/subscription/{subscriptionId}
  controller: MagentaCBookAdminBundle:BookReader:readNotif
  defaults:   { format: reference }

magenta_book_pwa_push_notif_subscription:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/subscribe-push-notification
  controller: MagentaCBookAdminBundle:BookPWA:savePushSubscription
  defaults:   { format: reference }

magenta_book_manifest:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/manifest.json
  controller: MagentaCBookAdminBundle:BookPWA:manifest
  defaults:   { format: reference }

magenta_book_service_worker:
  path:      /{orgSlug}/service-worker.js
  controller: MagentaCBookAdminBundle:BookPWA:serviceWorker
  defaults:   { format: reference }

magenta_book_app:
  path:      /{orgSlug}/app
  controller: MagentaCBookAdminBundle:BookReader:landing
  defaults:   { format: reference }

magenta_book_login:
  path:      /{orgSlug}/login
  controller: MagentaCBookAdminBundle:BookReader:login
  defaults:   { format: reference }

magenta_book_index:
  path:      /{orgSlug}/{accessCode}/{employeeCode}
  controller: MagentaCBookAdminBundle:BookReader:index
  defaults:   { format: reference }

magenta_book_archives_by_admin:
  path:      /{orgSlug}/admin-token/{adminCode}/archived-books/{bookId}
  controller: MagentaCBookAdminBundle:BookReader:bookArchivesByAdmin
  defaults:   { format: reference }

magenta_book_messages:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/messages
  controller: MagentaCBookAdminBundle:BookReader:messages

magenta_book_message_read:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/messages/{messageDeliveryId}/read
  controller: MagentaCBookAdminBundle:BookReader:readMessage

magenta_book_reader_book:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/book/{bookId}
  controller: MagentaCBookAdminBundle:BookReader:readBook
  defaults:   { format: reference }

magenta_book_reader_chapter:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/chapter/{chapterId}
  controller: MagentaCBookAdminBundle:BookReader:readChapter
  defaults:   { format: reference }

magenta_book_contact:
  path:      /{orgSlug}/{accessCode}/{employeeCode}/contact
  controller: MagentaCBookAdminBundle:BookReader:contact
  defaults:   { format: reference }
