<?php
declare(strict_types = 1);

namespace Magenta\Bundle\CBookModelBundle\Entity\Classification;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Magenta\Bundle\CBookModelBundle\Entity\Classification\Base\AppCollection;
use Sonata\ClassificationBundle\Entity\BaseCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */

/**
 * @ORM\Entity
 * @ORM\Table(name="classification__collection")
 * @ORM\HasLifecycleCallbacks
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="slug",
 *          column=@ORM\Column(
 *              name     = "slug",
 *              nullable = false,
 *              unique   = false,
 *     length   = 189
 *          )
 *      )
 * })
 */

class Collection extends AppCollection {

}
