<?php
declare(strict_types=1);

namespace Magenta\Bundle\CBookModelBundle\Entity\Classification;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Magenta\Bundle\CBookModelBundle\Entity\Classification\Base\AppContext;
use Sonata\ClassificationBundle\Entity\BaseContext;


/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
/**
 * @ORM\Entity
 * @ORM\Table(name="classification__context")
 * @ORM\HasLifecycleCallbacks
 */
class Context extends AppContext
{

}
