<?php

namespace Magenta\Bundle\CBookAdminBundle\Admin\Messaging;

use Aws\Api\Service;
use Magenta\Bundle\CBookAdminBundle\Admin\BaseCRUDAdminController;
use Magenta\Bundle\CBookAdminBundle\Service\Organisation\OrganisationService;
use Magenta\Bundle\CBookModelBundle\Entity\Organisation\Organisation;
use Magenta\Bundle\CBookModelBundle\Entity\System\DataProcessing\DPJob;
use Magenta\Bundle\CBookModelBundle\Service\ServiceContext;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;

class MessageAdminController extends BaseCRUDAdminController
{
    protected function redirectTo($object)
    {

        $request = $this->getRequest();

        if (null !== $request->get('btn_publish')) {
            $route = 'show';
            $url = $this->admin->generateObjectUrl($route, $object);
            return new RedirectResponse($url);
        }


        return parent::redirectTo($object);
    }

    public function listAction()
    {
        return parent::listAction(); // TODO: Change the autogenerated stub
    }
}
