<?php

namespace Magenta\Bundle\CBookAdminBundle\Admin\Organisation;


use Magenta\Bundle\CBookAdminBundle\Admin\BaseCRUDAdminController;

class IndividualMemberAdminController extends BaseCRUDAdminController
{
    public function listAction()
    {
        $this->admin->setTemplate('list', '@MagentaCBookAdmin/Admin/Organisation/IndividualMember/CRUD/list.html.twig');
        return parent::listAction(); // TODO: Change the autogenerated stub
    }
}
